"""fixed:message

Revision ID: 33f9929e5872
Revises: 20c72b8738e0
Create Date: 2026-07-12 15:43:38.214679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f9929e5872'
down_revision: Union[str, Sequence[str], None] = '20c72b8738e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_document_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_document_id_fkey'), 'messages', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
